name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
jobs: 
  check-application:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
            go-version: 1.21.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
     
      - run: go test
      - run: go run math.go

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: otavioomota/module-ci:latest